MeDo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("", include('accounts.urls')),
    path("", include("django.contrib.auth.urls")),
]




#handles the upload of media to database
urlpatterns = urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

main/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.home,name='home'),
    path("createNewList/", views.createNewList,name='createNewList'),
    path("addTask/", views.addTask,name='addTask'),
    path("deleteTask/", views.deleteTask,name='deleteTask'),
    path("editTask/", views.editTask,name='editTask'),
    path("saveChanges/", views.saveChanges,name='saveChanges'),
    path('updateStatus/',views.updateStatus,name="updateStatus"),
    path('deleteList/',views.deleteList,name="deleteList")


]

main/models.py
from django.db import models
from django.contrib.auth.models import User

#the toDolist model
class ToDoList(models.Model):
	#every created todoList must be related to a user,,setting null to true to avoid integrity error
	User = models.ForeignKey(User,on_delete=models.CASCADE,related_name='todolist', null=True)
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name




class Task(models.Model):
	todolist = models.ForeignKey(ToDoList,on_delete=models.CASCADE,related_name="task", null=True)
	text = models.CharField(max_length=200)
	completed = models.BooleanField()

main/forms.py
from django import forms

class CreateNewList(forms.Form):
    name = forms.CharField(label="ToDo List Name",max_length=100)
   

class CreateTask(forms.Form):
    text = forms.CharField(label="Task",max_length=200)
    completed = forms.BooleanField()

main/views.py
from django.shortcuts import render
from .models import ToDoList,Task
from . import forms
from django.http import JsonResponse
from bs4 import BeautifulSoup
import json
from django.contrib.auth.decorators import login_required
from accounts.views import signIn



@login_required
def home(request):
    # Get the New list form
    newListForm = forms.CreateNewList()

    # Get new task form
    newTaskForm = forms.CreateTask()


    #check if user has  todos
    todos_count = len(ToDoList.objects.filter(User=request.user.id))


    #check if user has tasks
    tasks_count = len(Task.objects.all())

    print(tasks_count)

    # Get all todo Lists related to the current user
    todos = ToDoList.objects.filter(User= request.user.id)

    current_list = todos.first()  # Set the default list



    # When the view button is clicked to change the selected todo
    if request.method == "POST" and request.POST.get('action') == "update_view":
        current_listID = request.POST.get("current_listID")
        current_list = ToDoList.objects.get(id=current_listID)
  

        tasks = Task.objects.filter(todolist=current_list)
        context = {
        "todos": todos,
        "newListForm": newListForm,
        "newTaskForm": newTaskForm,
        "selected_list": current_list,
        "tasks":tasks,
        "todos_count":todos_count,
        "tasks_count":tasks_count,
        }

        # Render the entire home view
        rendered_home_view = render(request, "main/home.html",{"context":context})

        # Extract the HTML content of the tasks section
        soup = BeautifulSoup(rendered_home_view.content, 'html.parser')
        tasks_html = str(soup.find('ul', class_='tasks'))



        # Return tasks HTML in JSON response
        return JsonResponse({'tasks_html': tasks_html})

        

    # Get tasks for the selected list
    tasks = Task.objects.filter(todolist=current_list)

    context = {
        "todos": todos,
        "newListForm": newListForm,
        "newTaskForm": newTaskForm,
        "selected_list": current_list,
        "tasks": tasks,
        "todos_count":todos_count,
        "tasks_count":tasks_count,
    }

    return render(request, "main/home.html", {"context": context})




#create new todo list
#request POSTed using ajax
def createNewList(request):
    #check if POST and get data
    if request.POST.get('action') == 'post':
        list_name = request.POST.get('list_name')

        #create an instance to ToDoList with the entered name
        newList = ToDoList(name=list_name)

        #save that instance to database
        newList.save()

        #link that saved todo list with the current user
        request.user.todolist.add(newList)


        #return response as json
        response = JsonResponse({'list name':list_name })
        return response



#delete todo list
def deleteList(request):
    if request.POST.get('action') == "deleteList":
        selected_list_id = request.POST.get('selected_list_id')

        
        #delete the list from database
        selected_list = ToDoList.objects.get(id=selected_list_id)

        selected_list.delete()

        print("deleted")


        response = JsonResponse({"list":selected_list_id})


        return response



#add a task
def addTask(request):
    #check if POST and get data
    if request.POST.get('action') == 'post':
        task = request.POST.get("task_text")
        completed = request.POST.get("completed").capitalize()
        selected_id = request.POST.get("current_listID")

        selected_list = ToDoList.objects.get(id=int(selected_id))

        newTask = Task(text=task,completed=completed)

        newTask.save()

        selected_list.task.add(newTask)


 
  

        tasks = Task.objects.filter(todolist=selected_list)
        context = {
        "tasks":tasks,

        }

        # Render the entire home view
        rendered_home_view = render(request, "main/home.html",{"context":context})

        # Extract the HTML content of the tasks section
        soup = BeautifulSoup(rendered_home_view.content, 'html.parser')
        tasks_html = str(soup.find('ul', class_='tasks'))



        # Return tasks HTML in JSON response
        return JsonResponse({'tasks_html': tasks_html})
        

         




#delete a task
def deleteTask(request):
    # Get all todo Lists related to the current user
    todos = ToDoList.objects.filter(User= request.user.id)

    current_list = todos.first()  # Set the default list


    if request.POST.get("action") == "deleteTask":
        clickedTaskID = request.POST.get("clickedTaskID")
        current_listID = request.POST.get("current_listID")
        current_list = ToDoList.objects.get(id=current_listID)

        #get the clicked task and delete it
        clicked = Task.objects.get(id=clickedTaskID)
        
        #delete it
        clicked.delete()


        tasks = Task.objects.filter(todolist=current_list)
        context = {
        "todos": todos,
        "selected_list": current_list,
        "tasks":tasks,
        }

        # Render the entire home view
        rendered_home_view = render(request, "main/home.html",{"context":context})

        # Extract the HTML content of the tasks section
        soup = BeautifulSoup(rendered_home_view.content, 'html.parser')
        tasks_html = str(soup.find('ul', class_='tasks'))


        #if keep count of tasks to refresh page when all tasks are deleted
        tasks_count = len(Task.objects.all())


        # Return tasks HTML in JSON response
        return JsonResponse({'tasks_html': tasks_html,"count":tasks_count})





#edit a task
def editTask(request):
    if request.POST.get("action") == "editTask":
        clickedTask = request.POST.get("clickedTask")

        response = JsonResponse({"task":clickedTask})

      

    return response





#save changes after editting
def saveChanges(request):
    if request.POST.get("action") == "saveChanges":

        #get ids of the editted tasks from the POST request
        tasks_ids = request.POST.getlist("inputs[]")

        #get current texts of the editted tasks from the POST request
        tasks_texts = request.POST.getlist("texts[]")

        #create a dict,keys are tasks id and value is task text
        editted_tasks = dict(zip(tasks_ids,tasks_texts))

        #get those editted tasks from db to update them
        tasks_to_edit = Task.objects.filter(id__in=tasks_ids) 



        for task_id in tasks_ids:
            for key,val in editted_tasks.items():
                if task_id == key:
                    Task.objects.filter(id=task_id).update(text=val)
                    print("updated")

                    


        response = JsonResponse({'task':editted_tasks})

        return response




#update task completion status
def updateStatus(request):
    if request.POST.get('action') == 'updateStatus':
        checkbox_id = request.POST.getlist('checkbox_id[]')[0] 
        checkbox_status = request.POST.getlist('checkbox_status[]')[0].capitalize() #to get True not true


        #get clicked task's from db and update its completion status
        Task.objects.filter(id=checkbox_id).update(completed=checkbox_status)


        response = JsonResponse({'checkbox':checkbox_id})

        return response

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>	{% block title %}{% endblock  %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'  %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/home.css'  %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css'  %}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

</head>
<body>



	<div class="body-container">

		<img src="{% static 'icons/todo.png' %}" class="logo">
		<div class="titles">
			<p id="webName">MeDo</p>
			<p id="webSlogan">Achieve Your Goals!!</p>
		</div>

		<div class="head-container">
			<div class="btn-group dropleft">
  <button type="button" class="btn btn-secondary " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  	Menu
  </button>
	<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
	  {% if user.is_authenticated %}
	      <a class="dropdown-item" href="{% url 'logout' %}">Sign Out</a>
	  
	  {% else %}
	  	<a class="dropdown-item" href="{% url 'login' %}">Sign In</a>

	  {% endif %}
	  <a class="dropdown-item" href="{% url 'home' %}">Home</a>
	  <a class="dropdown-item" href="{% url 'register' %}">Sign Up</a>
	</div>
</div>
			</div>


		{% block content %}


		{% endblock  %}


	</div>




<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script> <!--slim.js misses some functions-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'js/home.js' %}"></script>
<script type="text/javascript" src="{% static 'js/accounts.js' %}"></script>
</body>
</html>

main/templates/main/home.html
{% extends "main/base.html" %}

{% load static %}

{% block title %}MeDo-Home{% endblock  %}


{% block content %}

<div class="home-container">
	<button class="add-button"  id="add-button">
		<img class="add-image" src=" {% static 'icons/plus.png' %}">
	</button>
	<p id="newlistText">Create ToDo</p>

	{% if user.is_authenticated %}
	<div class="account-info">
		<img class="account-image" src="{% static 'icons/user.png' %}">
		<p class="account-name"> {{ user.username }} </p>
	</div>

	{% endif %}


	<div class="createListPopup" id="popup">
		<form method="POST">
			{% csrf_token %}
			{{ context.newListForm.as_table }}
			<button id="new-list-btn">Create</button>
		</form>
	</div>


	<div class="tasks-view" id="tasks-view">


		{% if context.todos_count > 0 %}
			
		
			<form class="select-form" method="POST">
				{% csrf_token %}
			<select name="todos" id="todos">
				{% for todo in context.todos  %}
					<option id="select_option" value="{{ todo.id }}"
					{% if todo == context.selected_list %}
						selected 
					{% endif %}
					>{{ todo }}</option>
				{% endfor %}

			</select>
			<button type="submit" class="filter-btn" id="filter-btn">View</button>
			<button type="submit" class="delete-btn" id="delete-btn">Delete</button>		
			</form>

		{% endif %}


		<div class="tasks-container">

			{% if context.tasks_count < 1 and context.todos_count > 0 %}
			    			
				<div class="taskEmpty-container" id="taskEmpty-container">
					<p id="addTasks_text">You have no tasks.</p>
					<img id="emptyTask_image" src="{% static 'icons/no-task.png' %}">
				</div>

			{% endif %}

		<form class="list-form" method="POST">
			{%csrf_token%}
			<ul class="tasks" id="tasks">


				{% for 	task in context.tasks  %}
					
				<li class="task"  id="task">
					<div class='task-div'>
						<div class="text-div">
							<p id="task_text"><input type="text" name="task-input" id="task-input{{task.id}}" class="task-input" data-index = "{{ task.id }}" value="{{ task.text }}" readonly></p>
						</div>
						<div class="edits-container">
							<input  class="completed-checkBox" type="checkbox"
							{% if task.completed %}
								checked
							{% endif %}
							data-index="{{ task.id }}"
							>
							<button class="edit-button"  id="edit-button" data-index="{{ task.id }}">
								<img class="image" src="{% static 'icons/pencil.png' %}">
							</button>
							<button class="del-button"  id="del-button" data-index="{{ task.id }}">
								<img class="image" src="{% static 'icons/delete.png' %}">
							</button>
						</div>
					</div>
				</li>
				{% endfor %}
					
			</ul>
		

		</form> 

		{% if context.todos_count < 1 %}

		<div class="noTasks-container">
			<p id="noTasks_text">Create a Todolist and add tasks. </p>
			<img class="noTask-image" src="{% static 'icons/noTask.png' %}">
		</div>	
		{% endif %}



		{% if context.todos_count > 0 %}
		
		<button class="add-task-btn"  id="addTask-button">
			<img class="addTask-image" src=" {% static 'icons/plus.png' %}">
		</button>			    
					
		{% endif %}			


		<div class="new-task-form" id="new-task-form">
			<form method="POST">
				{% csrf_token %}
				{{ context.newTaskForm.as_table }}
				<button id="task-add-btn">Add</button>			
			</form>
		</div>

		</div>

	</div>


		{% if context.todos_count > 0 and context.tasks_count > 0  %}
		
			<form method="POST">
				{% csrf_token %}
				<button class="list-save-btn" id="list-save-btn" type="submit">Save Changes</button>
			</form>			    
							
		{% endif %}		


</div>



<script >

//send a post request to create new list
//opted to put this code within the html file since the django url tag doesn't work in js file
$(document).on('click', '#new-list-btn', function(e){


	if($('#id_name').val() == ""){
		alert("Please enter the new to do list name!!");
		return false;
	}


	e.preventDefault(); //prevents elements default operations like auto submitting btn
	$.ajax({
		//the method and url to be used
		type: "POST",  					  //type of request
		url : "{% url 'createNewList' %}", //the url to be used so that the correct view is called

		//the data to be sent using POST
		data : {
			list_name : $("#id_name").val(),
			csrfmiddlewaretoken : '{{ csrf_token }}',
			action : 'post'  //use this 'action' to check id this data packet is POSTED
		},

        success: function(json){
            location.reload()
           
        },


        error : function(xhr,errmsg,err){
        	
        }		
	})
})




// add a task to a todoList
$(document).on('click', '#task-add-btn', function(e){

	if($('#id_text').val() == ""){
		alert("Please enter the new to do list name!!");
		return false;
	}

	e.preventDefault(); //prevents elements default operations like auto submitting btn
	$.ajax({
		//the method and url to be used
		type: "POST",  					  //type of request
		url : "{% url 'addTask' %}", //the url to be used so that the correct view is called

		//the data to be sent using POST
		data : {
			task_text : $("#id_text").val(),
			completed : $('#id_completed').is(":checked"),
			current_listID : $('#todos option:selected').val(),
			csrfmiddlewaretoken : '{{ csrf_token }}',
			action : 'post'  //use this 'action' to check id this data packet is POSTED
		},

        success: function(data){
        	//change the content of the tasks ul with the new updated content
        	$('.tasks').html(data.tasks_html);

        	task = document.getElementById("tasks");
        	task.style.marginLeft = "-2.2rem";


        	//clear task input and hide it
        	let taskInput = document.getElementById('id_text');
        	let taskContainer = document.getElementById("new-task-form");

        	taskInput.value = "";
        	taskContainer.style.display = "none";
           
        },


        error : function(xhr,errmsg,err){
        	
        }		
	})
})



//delete todo list
$(document).on("click", "#delete-btn",function(e){
	e.preventDefault();

	$.ajax({
		type : 'POST',
		url : '{% url "deleteList" %}',

		data : {
			selected_list_id : $("#select_option").val(),
			csrfmiddlewaretoken : '{{ csrf_token }}',
			action : 'deleteList',

		},


		success : function(data){
			location.reload();
			alert("list deleted!");

		},

		error : function(xhr,errmsg,err){

		}
	})
})


// display the tasks of the selected list
$(document).on('click', '#filter-btn', function(e){
	e.preventDefault(); //prevents elements default operations like auto submitting btn
	$.ajax({
		//the method and url to be used
		type: "POST",  					  //type of request
		url : "{% url 'home' %}", //the url to be used so that the correct view is called

		//the data to be sent using POST
		data : {
			current_listID : $('#todos option:selected').val(),
			current_list : $('#todos option:selected').text(),
			csrfmiddlewaretoken : '{{ csrf_token }}',
			action : 'update_view',  //use this 'action' to check id this data packet is POSTED
		},

        success: function(data){
        	//change the content of the tasks ul with the new updated content
        	$('.tasks').html(data.tasks_html);

        	task = document.getElementById("tasks");
        	task.style.marginLeft = "-2.2rem";

        	

        },


        error : function(xhr,errmsg,err){
        	
        }		
	})
})




//delete a task
$(document).on('click', '#del-button', function(e){
	e.preventDefault(); //prevents elements default operations like auto submitting btn
	$.ajax({
		//the method and url to be used
		type: "POST",  					  //type of request
		url : "{% url 'deleteTask' %}", //the url to be used so that the correct view is called


		//the data to be sent using POST
		data : {
			clickedTaskID  :  $(this).data("index"),
			current_listID : $('#todos option:selected').val(),
			csrfmiddlewaretoken : '{{ csrf_token }}',
			action : 'deleteTask',  //use this 'action' to check id this data packet is POSTED
		},

        success: function(data){
        	//change the content of the tasks ul with the new updated content
        	$('.tasks').html(data.tasks_html);

        	task = document.getElementById("tasks");
           	task.style.marginLeft = "-2.2rem";

           	count = parseInt(data.count);

           	//reload page if all tasks are deleted to display no tasks image
           	if(count < 1){
           		location.reload();
           	}
 	

        },


        error : function(xhr,errmsg,err){
        	
        }		
	})
})




//edit task
$(document).on('click', '#edit-button', function(e){
	e.preventDefault(); //prevents elements default operations like auto submitting btn

	//get the data index of the clicked edit buttn
	var btnIndex =  $(this).data("index");
	var idName = "task-input" + btnIndex;

	$.ajax({
		//the method and url to be used
		type: "POST",  					  //type of request
		url : "{% url 'editTask' %}", //the url to be used so that the correct view is called

		//the data to be sent using POST
		data : {

			//get clicked task using its id
			clickedTask : $('#idName').val(),
			csrfmiddlewaretoken : '{{ csrf_token }}',
			action : 'editTask',  //use this 'action' to check id this data packet is POSTED
		},

        success: function(data){
        	//get the clicked task input and remove the readonly attribute
        	const clicked_task = document.getElementById(idName);
        	

        	//remove readonly attribute
        	clicked_task.removeAttribute('readonly');
        	clicked_task.focus();

        },


        error : function(xhr,errmsg,err){
        	
        }		
	})
})





//save changes after edit
$(document).on('click', '#list-save-btn', function(e){
	e.preventDefault(); //prevents elements default operations like auto submitting btn

	//get editted task id
	var taskInputs = [];

	//get editted task text
	var tasksText = [];

	$('.task-input').each(function() {
	    if(this.readOnly == false){
	        var index = $(this).data("index");
	        var text = $(this).val();
	        if (typeof index !== 'undefined') {
	            taskInputs.push(index);
	            tasksText.push(text);
	        }
	    }
	});


	

	

	$.ajax({
		//the method and url to be used
		type: "POST",  					  //type of request
		url : "{% url 'saveChanges' %}", //the url to be used so that the correct view is called
	

		//the data to be sent using POST
		data : {

			inputs : taskInputs,
			texts : tasksText,
			csrfmiddlewaretoken : '{{ csrf_token }}',
			action : 'saveChanges',  //use this 'action' to check id this data packet is POSTED

		},

        success: function(data){

   
        },


        error : function(xhr,errmsg,err){
        	
        }		
	})
})



//update task status
$(document).on('click','.completed-checkBox',function(e){


	//to store ids of the clicked checkboxes
	var clicked_checkbox_id = [];


	//to store status of the clicked checkboxes
	var clicked_checkbox_state = [];


	//get the clicked checkbox id(index)
	index = $(this).data("index");
	clicked_checkbox_id.push(index);


	//get the clicked checkbox state
	status = $(this).is(" :checked");
	clicked_checkbox_state.push(status);


	$.ajax({
		type:"POST",
		url:"{% url 'updateStatus' %}",

		data : {
			checkbox_id : clicked_checkbox_id,
			checkbox_status : clicked_checkbox_state,
			csrfmiddlewaretoken : '{{ csrf_token }}',
			action : "updateStatus",
		},


		success : function(data){
		},


        error : function(xhr,errmsg,err){
        	
        }
	})

})

</script>



{% endblock  %}